### ISSUE TITLE
Am I blind? Can't find where to set API mode.

### ISSUE THREAD

**Issue by DrakePork** [Kas-tle/EnjinScraper#18]
Am I just missing the API mode button or is it somewhere else and not in the API tab in settings?

![axcvbxcvb](https://user-images.githubusercontent.com/29175884/233732475-3fc588a6-3ba2-4757-b6b2-aaaaffa850d2.PNG)

**Comment by Kas-tle** [comment]
Are you the site owner? Or is this just an admin account?

**Comment by HippieBeak** [comment]
I think you just have to click the “create API key” button

**Comment by DrakePork** [comment]
Site owner, but seems like the scraper now works when I try it even though it didn't 5 minutes ago. So I'll close this.
