### ISSUE TITLE
Forum scraping issues

### ISSUE THREAD

**Issue by DrakePork** [Kas-tle/EnjinScraper#20]
The scraper successfully scrapes everything else but the forums for me (I disabled forum in the config to test)
It's not throwing any errors, it just receives the exit signal and closes.
First time running it:
```
[X] Site data already scraped, moving on...
[i] Scraping forums...
[i] Starting at... Module count: 0 Forum count: 0 Thread count: 0
[i] Added exit listeners for recovery. Press Ctrl+C to exit and write current object to file.
Inserted 10273185 into table 'forum_modules'
Inserted 70 rows into table 'forums'
[•] Found 70 forums in module 10273185... [(1/1)]
[X] Exit signal 1 received, writing current object to file...
```

Running it subsequent times:
```
[X] Site data already scraped, moving on...
[i] Scraping forums...
[i] Recovering from previous session...
[i] Starting at... Module count: 1 Forum count: 0 Thread count: 0
[i] Added exit listeners for recovery. Press Ctrl+C to exit and write current object to file.
[X] Exit signal 1 received, writing current object to file...
```
I tried to use the exclude forum module id to see if excluding most of the forums would fix it, but it did not.

**Comment by DrakePork** [comment]
Found the issue!

Messed around with the forums.ts and removed exit listeners from it, which did result in me getting this error:
```
TypeError: notices is not iterable
    at C:\Users\Andreas\Documents\GitLab\EnjinScraper\src\scrapers\forums.ts:161:90
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Andreas\Documents\GitLab\EnjinScraper\src\scrapers\forums.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Seems like its failing to iterate through notices at
```const allThreads = [...announcement_global, ...announcement_local, ...sticky, ...notices, ...threads];```

So I deleted the global notice I had on the forum and it started to work.

So yeah seems like if you have a global notice the program doesn't know what to do with it so exits.

**Comment by Kas-tle** [comment]
From debug could you send what the response from the enjin api for Forum.getForum that contains what the global announcement looked like?

**Comment by DrakePork** [comment]
```
"notices": {
                "notice_id": "12337",
                "preset_id": "10273185",
                "name": "THIS FORUM IS NO LONGER IN USE",
                "description": "[highlight=#dd2423]WE HAVE MOVED TO A NEW FORUM! PLEASE [url=https://example.com]CLICK ME[/url] TO GO THERE![/highlight]",
                "show": "now",
                "expires": "delete",
                "show_days": "1",
                "expire_days": "1",
                "expire_date": "1613088000",
                "page_location": "all",
                "user_id": "4417816",
                "viewed": "1507670005",
                "deleted": "0",
                "notice": "<span class=\"bbcode-highlight\" style=\"background-color:#dd2423\">WE HAVE MOVED TO A NEW FORUM! PLEASE <a rel=\"nofollow noopener\" href=\"https://example.com\" class=\"bbcode_url\" title=\"https://example.com\" data-safe-url=\"https://example.com\">CLICK ME</a> TO GO THERE!</span>",
                "total": 1,
                "page": 1
            }
```

**Comment by Kas-tle** [comment]
Ah the site I developed this for did not have notices so I think I assumed notices was just an array of thread stats because it was... plural (notices) but based on what you've provided here it looks like there can only be one notice and it has nothing to do with a thread, so notices should just be omitted from all threads then.

**Comment by Kas-tle** [comment]
Does it allow you to set multiple notices for one forum?

**Comment by DrakePork** [comment]
Yeah.
![image](https://user-images.githubusercontent.com/29175884/233790685-070ce50c-7fe0-4966-8613-0202fe05cc26.png)
![image](https://user-images.githubusercontent.com/29175884/233790673-ffd0a89a-7a56-4677-8a97-27128134681e.png)

**Comment by Kas-tle** [comment]
Hmmm. Could you just check what the api response looks like when there are multiple notices then?

**Comment by DrakePork** [comment]
```
            "notices": {
                "notice_id": "13376",
                "preset_id": "10273185",
                "name": "Test",
                "description": "test",
                "show": "now",
                "expires": "delete",
                "show_days": "1",
                "expire_days": "1",
                "expire_date": "0",
                "page_location": "all",
                "user_id": "4417816",
                "viewed": "1682174046",
                "deleted": "0",
                "notice": "test",
                "total": 2,
                "page": 1
            }
```
![image](https://user-images.githubusercontent.com/29175884/233791000-f0a5ad4a-dd46-4b38-80bc-72615fbb449f.png)

**Comment by Kas-tle** [comment]
Huh. So then there's probably just no way to get it from the api then based on this...

**Comment by Kas-tle** [comment]
Regardless this should be fixed by https://github.com/Kas-tle/EnjinScraper/commit/5eeabd95308b5feff99ef093914bdc7cf429e487. Thanks for your help with debugging this. I will look into if there's any way to save the notices to the db if there are more than one.

**Comment by Kas-tle** [comment]
It seems there is an undocumented API endpoint for Forums called Forum.getNotices so I have used this to add the notices to the database in case there are any present; see https://github.com/Kas-tle/EnjinScraper/commit/84571bfe1e59b18f1f1f869ceae7defb29d782b4.
