### ISSUE TITLE
HTTP/524 Timeout

### ISSUE THREAD

**Issue by allquixotic** [Kas-tle/EnjinScraper#21]
The Enjin API throws an HTTP/524 Timeout when scraping my forum. I think it might be because a specific page of a specific thread takes too long for Enjin to return from its API, so the Axios API throws a timeout.

BTW, this problem is repeatable. Can we extend the timeout on the client or will that not help?

**Comment by Kas-tle** [comment]
Doesn't this error come from Cloudflare though? I thought that implies that the host (enjin) timed out?

**Comment by Kas-tle** [comment]
https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-524-a-timeout-occurred at least according to this Cloudflare sets this at 100 seconds from when cloudflare proxies the request to the backend... so I don't think there's anything we can do about it.

Edit: If possible you could disable SSL on your site to prevent traffic from being proxied through CF, but given the state of Enjin at this point that could just end up bricking your site.

**Comment by allquixotic** [comment]
OK; so if this happens, can EnjinScraper catch the error and retry rather than dumping out with a stack trace?

If the Enjin backend craps the bed overnight, it would be nice if the tool would just standby and patiently wait for it to come back and then resume scraping, rather than failing out and needing to be kicked again to resume. :)

**Comment by Kas-tle** [comment]
Certainly could be added here... https://github.com/Kas-tle/EnjinScraper/blob/main/src/util/request.ts. Should it try again, or just skip?

**Comment by allquixotic** [comment]
I know this tool won't be of much use in a few days, but for folks who want to do large, hands-off guild site extractions from now until the end of Enjin, I'm thinking the best design might be :

Create 2 config parameters 

1. skipOnTimeout = true/false - if true, it will skip requests that timeout with a 524
2. retryOnTimeout = true, false, or a non-negative integer. 
 - If retryOnTimeout is true, retries up to 5 times on receiving an HTTP/524.
 - If retryOnTimeout is false, this is equivalent to *NEVER* retrying.
 - If retryOnTimeout is 0, retry an infinite number of times. In other words, if the backend continuously throws HTTP/524, the program will get stuck in an infinite loop. Intended behavior.
 - If retryOnTimeout is a positive integer, retry that number of times.
 
 If retryOnTimeout is a non-negative integer or `true` (== 5) *and* skipOnTimeout is also `true`, then the scraping process will first try `retryOnTimeout` number of times, then skip over the current request, log the problem and continue with the scraping without capturing any data from the current request into the DB. 
 
 If retryOnTimeout is true or non-negative integer and skipOnTimeout is `false`, then after the specified number of attempts has been exceeded of receiving consecutive HTTP/524, the program will panic and throw a stack trace.
 
 If retryOnTimeout is `false` and skipOnTimeout is `true`, any request that gives an HTTP/524 will result in that request being skipped immediately without a retry.

If retryOnTimeout is `false` and skipOnTimeout is `false`, the current behavior of EnjinScraper will apply (immediately dump stack and exit).

Of these, my guild would use the condition where retryOnTimeout is 0 and skipOnTimeout is false. If you'd rather just hard-code that rather than the flexible options, that's fine too.

This design is based on the expectation that:

 - During "normal operation" (or what's left of it) of Enjin, it won't throw HTTP/524.
 - HTTP/524 will be thrown continuously while Enjin is "down" (site overloaded, patch causing server reboot, out of memory error resulting in restart of the web server, etc.).
 - Once Enjin restores functionality of the site, the HTTP/524 will go away and requests will succeed again.

**Comment by Kas-tle** [comment]
The retry is fairly easy to implement... skipping though not so much because whether it is something that can be skipped really depends on the context of the request... and so I'd have to go and classify what can and cannot be skipped for basically everywhere a web request is made... you can imagine for example if authentication fails we can't really skip it, but if getting a single user's wall post fails then sure we can...

So I will implement the retry system as that can be easily implemented by only modifying the request system.

**Comment by Kas-tle** [comment]
```jsonc
{
    "apiKey": "someapiKey", // Required
    "domain": "www.example.com", // Required
    "email": "someemail@email.com", // Required
    "password": "somepassword", // Required
    "disabledModules": {
        "forums": false,
        "galleries": false,
        "news": false,
        "wikis": false,
        "tickets": false,
        "applications": false,
        "comments": false,
        "users": {
            "ips": false,
            "tags": false,
            "fullinfo": true,
            "characters": true,
            "games": true,
            "photos": true,
            "wall": true
        },
        "files": {
            "s3": false,
            "wiki": false,
            "avatars": true,
            "profileCovers": true,
            "gameBoxes": true,
            "userAlbums": true
        }
    },
    "retrySeconds": 5, // Setting to 0 will retry instantly
    "retryTimes": 5, // Setting to 0 will disable retries; setting to -1 will retry indefinitely
    "debug": false,
    "disableSSL": false
}
```
