### ISSUE TITLE
Are images embedded in forum posts supported?

### ISSUE THREAD

**Issue by allquixotic** [Kas-tle/EnjinScraper#22]
Does the tool support extracting images embedded in forum posts (e.g. in bbcode `[img]` tags)?

If not, is this something that the tool should do?

**Comment by Kas-tle** [comment]
I mean it downloads everything on s3 for your site so that should get all forum attachments. Given that I don't think we need to parse thread posts in that manner.

**Comment by allquixotic** [comment]
That's acceptable. Thanks!

**Comment by Kas-tle** [comment]
FYI they should be under `target/files/s3.amazonaws.com/files.enjin.com/${siteID}/modules/forum/attachments`
